CREATE ROLE rucioreplicant WITH REPLICATION LOGIN PASSWORD 'rucio777';
GRANT ALL PRIVILEGES ON DATABASE rucio TO rucioreplicant;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rucioreplicant;
CREATE PUBLICATION rucio_publication;
ALTER PUBLICATION rucio_publication ADD TABLE widgets;