# Copyright 2014-2018 CERN for the benefit of the ATLAS collaboration.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Thomas Beermann, <thomas.beermann@cern.ch>, 2018

version: "2"
services:
  rucio-client:
      build:
        context: ./rucio-client
        dockerfile: Dockerfile
      image: slidspitfire/rucio-client:latest
      container_name: rucio-client
      depends_on:
        - "rucio-server"
        - "rucio-db"
      networks:
      - rucionetwork
      tty: true
  rucio-ui:
    build:
      context: ./rucio-ui
      dockerfile: Dockerfile
    image: slidspitfire/rucio-ui:latest
    container_name: rucio-ui
    ports:
      - "443:443"
    depends_on:
      - "rucio-db"
    networks:
      - rucionetwork
    command: ["httpd", "-D", "FOREGROUND"]
  rucio-server:
    build:
      context: ./rucio-server
      dockerfile: Dockerfile
    image: slidspitfire/rucio-server:latest
    container_name: rucio-server
    ports:
      - "9443:443"
    networks:
      - rucionetwork
    depends_on:
      - "rucio-db"
    command: ["httpd", "-D", "FOREGROUND"]
  rucio-db:
    build:
      context: ./rucio-db-master
      dockerfile: Dockerfile
    image: slidspitfire/rucio-db-master:latest
    container_name: rucio-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD="pippo123"
    networks:
      - rucionetwork
  rucio-db-slave:
    build:
      context: ./rucio-db-slave
      dockerfile: Dockerfile
    image: slidspitfire/rucio-db-slave:latest
    container_name: rucio-db-slave
    ports:
      - "54320:5432"
    networks:
      - rucionetwork
    environment:
      - POSTGRES_PASSWORD="pippo123"

networks:
  rucionetwork:
    driver: bridge
